<div class="vitrine-aviso">Demonstração interativa — ligue e desligue os avisos (dados fictícios, nada é salvo).</div>
<section class="cfg-painel active" id="cfg-notificacoes">
    <div class="config-bloco">
        <div class="config-bloco-header"><h2>Notificações</h2><span class="vit-resumo" id="vitResumo"></span></div>
        <p class="config-bloco-sub">Preferências pessoais — valem só pra sua conta, em qualquer terminal que você usar.</p>
        <div class="config-item config-item--pref"><div class="config-item-texto"><strong>Aviso de chamado respondido</strong><span>Mostra um alerta rápido na tela quando um chamado seu no Suporte for respondido.</span></div><label class="config-switch"><input type="checkbox" id="vitSw_suporte" checked data-gc-change="vitToggle('suporte', this)"><span class="config-switch-track"></span></label></div><div class="config-item config-item--pref"><div class="config-item-texto"><strong>Nova ocorrência aberta</strong><span>Avisa quando alguém registrar uma ocorrência (reclamação, retorno de prato, avaria...).</span></div><label class="config-switch"><input type="checkbox" id="vitSw_ocorrencia" checked data-gc-change="vitToggle('ocorrencia', this)"><span class="config-switch-track"></span></label></div><div class="config-item config-item--pref"><div class="config-item-texto"><strong>Ruptura de estoque</strong><span>Alerta quando um item chega a zero — e quando ele volta ao estoque.</span></div><label class="config-switch"><input type="checkbox" id="vitSw_ruptura" checked data-gc-change="vitToggle('ruptura', this)"><span class="config-switch-track"></span></label></div><div class="config-item config-item--pref"><div class="config-item-texto"><strong>Preço aguardando aprovação</strong><span>Avisa quando um preço sugerido entra na fila pra você aprovar ou rejeitar.</span></div><label class="config-switch"><input type="checkbox" id="vitSw_preco" data-gc-change="vitToggle('preco', this)"><span class="config-switch-track"></span></label></div><div class="config-item config-item--pref"><div class="config-item-texto"><strong>Chamado de manutenção resolvido</strong><span>Avisa quando um equipamento que você reportou for consertado.</span></div><label class="config-switch"><input type="checkbox" id="vitSw_manut" data-gc-change="vitToggle('manut', this)"><span class="config-switch-track"></span></label></div><div class="config-item config-item--pref"><div class="config-item-texto"><strong>Resumo semanal por e-mail</strong><span>Toda segunda-feira, um e-mail com CMV, CMO e as principais ocorrências da semana.</span></div><label class="config-switch"><input type="checkbox" id="vitSw_email" data-gc-change="vitToggle('email', this)"><span class="config-switch-track"></span></label></div>
        <div class="vit-acoes">
            <button class="sup-btn-acao" data-gc-click="vitTodos(true)">Ligar todos</button>
            <button class="sup-btn-acao" data-gc-click="vitTodos(false)">Desligar todos</button>
        </div>
    </div>
</section>
<div class="toast" id="vitToast"><span id="vitToastMsg"></span><button class="toast-fechar" data-gc-click="document.getElementById('vitToast').classList.remove('show')">&times;</button></div>
